/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_demo_NativeCrypto */

#ifndef _Included_com_example_demo_NativeCrypto
#define _Included_com_example_demo_NativeCrypto
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_demo_NativeCrypto
 * Method:    encryptData
 * Signature: ([BI[B)J
 */
JNIEXPORT jlong JNICALL Java_com_example_demo_NativeCrypto_encryptData
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray);

/*
 * Class:     com_example_demo_NativeCrypto
 * Method:    decryptData
 * Signature: (J[B)J
 */
JNIEXPORT jlong JNICALL Java_com_example_demo_NativeCrypto_decryptData
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_example_demo_NativeCrypto
 * Method:    createEncryptedData
 * Signature: ([BI[B)J
 */
JNIEXPORT jlong JNICALL Java_com_example_demo_NativeCrypto_createEncryptedData
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray);

/*
 * Class:     com_example_demo_NativeCrypto
 * Method:    getCiphertext
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_demo_NativeCrypto_getCiphertext
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_example_demo_NativeCrypto
 * Method:    getIV
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_demo_NativeCrypto_getIV
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_example_demo_NativeCrypto
 * Method:    getPlaintext
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_demo_NativeCrypto_getPlaintext
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_example_demo_NativeCrypto
 * Method:    freeMemory
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_demo_NativeCrypto_freeMemory__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_example_demo_NativeCrypto
 * Method:    freeMemory
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_example_demo_NativeCrypto_freeMemory___3B
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_example_demo_NativeCrypto
 * Method:    freeEncryptedData
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_demo_NativeCrypto_freeEncryptedData
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_example_demo_NativeCrypto
 * Method:    freeDecryptedData
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_demo_NativeCrypto_freeDecryptedData
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_example_demo_NativeCrypto
 * Method:    serializeEncryptedData
 * Signature: (J[I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_demo_NativeCrypto_serializeEncryptedData
  (JNIEnv *, jobject, jlong, jintArray);

/*
 * Class:     com_example_demo_NativeCrypto
 * Method:    deserializeEncryptedData
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_example_demo_NativeCrypto_deserializeEncryptedData
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
